global: 
  scrape_interval: 5s
  external_labels: 
    monitor: codelab-monitor

scrape_configs: 
  - job_name: prometheus-system
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: prometheus-client
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus-client:80"]
